Maps conflict cholera
OCHA-DAP/ds-som-risk-analysis-support pull request #2
Opened 2023-10-05 21:28 UTC by zackarno

Projects still largely in brainstorming phase but with a sense of urgency because they want analysis reviewed by other partners by the 15th. Let's DM off github so I can catch you up on latest conversations.

Given the urgency, I am very open and welcoming of suggestions for additional analysis ideas but i think it might make sense to pose them using the [discussion](https://github.com/OCHA-DAP/ds-som-risk-analysis-support/discussions) feature OR on slack I just initiated for this repo. I think that will allow us to keep the branches tighter in scope and allow us to move more quickly with validating/merging given the timeline. Basically I want the PRs/reviews to prioritize catching any glaring errors in code &  fixing if necessary -- and we save more brainstormy type stuff for discussions?

Let me know if this makes sense and if you have any questions on the approach and/or code

2023-10-06 19:18 UTC, zackarno commented
Thanks for all the useful suggestions on slack! I just pushed a commit where I integrate the `ACLED` `actor` attributes so that I can classify conflict events as `Interclan` vs `Non-Intl Armed (Shabaab)`.  I also updated the slides.

My plan is to work w/ the slides and the repo in parallel - right now it's just brainstorming with everything in the `exploration` folder and almost all (if not all) plots in the slides. As I trim down the slides based on internal and external feedback - I will cut the relevant code from the exploration documents into a notebook(s) that will go into an `analysis` folder.

2023-10-09 12:11 UTC, caldwellst commented
Nice, for now, won't review anything until ready, and even then, will just be the analysis, don't think there's a need for full detailed code review on the exploration.

2023-10-17 11:51 UTC, caldwellst requested changes
Hey hey! Cholera looks good, methods are obviously much simpler and check out. I think a valuable visualisation might be comparing year on the trends by plotting with epiweek on the x axis. Can make for easier yearly comparison that way. But probably not worth putting much more effort into it.

I did request some changes to the conflict stuff. Not sure why `riots` was used as one of the violent events in the filter, but that isn't normally one of them, the violent event missing is for remote violence/explosives (IEDs, drones, missile strikes, that kinda thing), which is definitely going to have at least some cases of in Somalia.

Otherwise, looks good!

2023-10-17 11:51 UTC, caldwellst commented on analysis/01_Conflict_ACLED_slides.Rmd
> +  scale_y_continuous(breaks = seq(-600, 700, 50)) +
They work, obviously, just that they don't reach the max values.

2023-10-17 13:30 UTC, zackarno commented on analysis/01_Conflict_ACLED_slides.Rmd
> +    "Riots",
woops - nice catch! [60de127](https://github.com/OCHA-DAP/ds-som-risk-analysis-support/pull/2/commits/60de1271a0b75857fbc2452955b621074d79010b)

2023-10-17 13:30 UTC, zackarno commented on analysis/01_Conflict_ACLED_slides.Rmd
> +         !(year == 2022 & event_date >= "2022-09-29")
yeah that's a good point. I've made them 100 % static as you suggested that way the analysis/graphs created here will be reproducible

[60de127](https://github.com/OCHA-DAP/ds-som-risk-analysis-support/pull/2/commits/60de1271a0b75857fbc2452955b621074d79010b)

2023-10-17 13:32 UTC, zackarno commented on analysis/01_Conflict_ACLED_slides.Rmd
> +  scale_y_continuous(breaks = seq(-600, 700, 50)) +
oh yeah I see - good call.   I adjusted them for clearer/improved output

2023-10-17 14:19 UTC, caldwellst approved these changes

2023-10-17 17:40 UTC, merged